Feat/add hist fitler#34
kostas-vl/bld pull request #43
Opened 2022-10-01 21:11 UTC by AlkisChristidis

Review @kostas-vl  onegai.

2022-10-01 21:12 UTC, AlkisChristidis commented
#34 #43 Is this a sign from kami-sama???? @AKaravokiris

2022-10-02 17:00 UTC, kostas-vl commented on bld_commands/src/hist/command.rs
>          SubCommand::with_name(HIST)
The state argument is not included in the Subcommand

```suggestion
        SubCommand::with_name(HIST)
            .about("Fetches execution history of pipelines on a server")
            .version(VERSION)
            .args(&[server, state])
```

2022-10-02 17:02 UTC, kostas-vl commented on bld_server/src/endpoints/hist.rs
> +#[get("/hist/state/:")]
Since we pass the state as a query parameter the url should be presented like 
```suggestion
#[get("/hist")]
```

2022-10-02 17:06 UTC, kostas-vl commented on bld_server/src/endpoints/hist.rs
>  }
We can use a struct to represent all available query parameters e.g.
```rust
#[derive(Debug, Serialize, Deserialize)]
pub struct HistQueryParams {
    state: String,
}
```
and then use this struct in the function argument
```rust
pub async fn hist(
    query: Query<HistQueryParams>,
    user: Option<User>,
    db_pool: Data<Pool<ConnectionManager<SqliteConnection>>>,
) -> impl Responder {
    info!("Reached handler for /hist route");
    if user.is_none() {
        return HttpResponse::Unauthorized().body("");
    }
    let query = query.into_inner();
    match history_info(db_pool.get_ref(), &query.state) {
        Ok(ls) => HttpResponse::Ok().body(ls),
        Err(_) => HttpResponse::BadRequest().body(""),
    }
}
```

2022-10-02 17:08 UTC, kostas-vl requested changes
Added comments for some required changes.

I think it would be useful to have a --limit argument in order to set the maximum number of entries returned.

2022-10-28 00:05 UTC, AlkisChristidis commented
Implemented the changes directly to the upstream.

2022-10-28 00:05 UTC, closed without merging